### ISSUE TITLE
BibTex for citing

### ISSUE THREAD

**Issue by elcronos** [dribnet/perceptionengines#4]
Hi Tom,

Your work is very inspiring and interesting. I'm planning to submit a paper soon and was wondering if you have any paper related to your work on perception engines or synthetic abstraction that I can cite. The idea of neural networks being able to learn high-level abstract features is very intriguing and I'd like to explore a bit more this area in the future.

Thanks.

**Comment by dribnet** [comment]
Thanks for your message. The best current academic reference would be my paper [Shared Visual Abstractions](https://arxiv.org/abs/1912.04217) which appeared last year in the [SVRHM NeurIPS Workshop](https://www.svrhm2019.com/home).

```txt
@abstract{2019a,
  author = "Tom White",
  title = "Shared Visual Abstractions",
  year = 2019,
  journal = "NeurIPS Workshop: Shared Visual Representations in Human & Machine Intelligence",
  month = "Dec",
  url = "https://arxiv.org/abs/1912.04217"
}
```

**Comment by elcronos** [comment]
@dribnet Thanks Tom. I added that reference in my paper.
